MobileShop/MobileShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [	
	path('',include('mobilestore.urls',namespace='mobilestore')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

MobileShop/mobilestore/urls.py

from django.urls import path,include
from .views import Homepage,MobileList, MobileDetail, AddMobile,UpdateMobile,DeleteMobile

app_name ='mobilestore'
#urlpatterns = [	
# 	path('',('mobilestore.urls',namespace='mobilestore')),
  
# ]
urlpatterns=[

 	path('',Homepage ,name='cssintro'),
	path('MobileList/',MobileList ,name='mobilelist'),
	path('MobileList/<int:id>',MobileDetail ,name='MobileDetail'),
	path('AddMobile/',AddMobile ,name='AddMobile'),
	path('mobileupdate/<int:id>',UpdateMobile,name='mobileupdate'),
	path('mobiledelete/<int:id>',DeleteMobile,name='mobiledelete'),

]

MobileShop/mobilestore/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Mobile(models.Model):
	Model_Name          = 	 models.CharField(max_length=50)
	Image		        = 	 models.ImageField(upload_to='mobileImage')
	Brand               =	 models.CharField(max_length=50)
	Price	            =	 models.IntegerField()
	Descrption 			= 	 models.CharField(max_length=150,default="face recognition,13 mp cammera ")

	def __str__(self):
		return self.Model_Name

class Cart(models.Model):
	user 		= models.ForeignKey(User,on_delete=models.CASCADE)
	mobile      = models.ForeignKey(Mobile,on_delete=models.CASCADE)

	def __str__(self):
		return self.mobile.Model_Name	

MobileShop/mobilestore/forms.py
from django import forms
from .models import Mobile

class MobileForm(forms.ModelForm):
	class Meta:
		model =Mobile
		fields =['Model_Name','Image','Brand','Price','Descrption']

MobileShop/mobilestore/views.py
from django.shortcuts import render,redirect
from.models import Mobile
from django .http import Http404
from .forms import MobileForm
def Homepage(request):
	return render(request,'cssintro.html')


def MobileList(request):
		mobiles =Mobile.objects.all()
		context ={'mobiles':mobiles}
		return render(request,'mobilelist.html',context)

def MobileDetail(request,id):
		try:
			mobiles =Mobile.objects.get(id=id)
			context ={'mobiles':mobiles}
			return render(request,'MobileDetail.html',context)

		except Mobile.DoesNotExist:
			raise Http404
			

def AddMobile(request):
	if request.user.is_superuser:
			
			

		if request.method=='POST':
			form=MobileForm(request.POST,request.FILES)
			if form.is_valid():
				form.save()
				return redirect('mobilestore:mobilelist')
		else:
			form=MobileForm()
		context={'form':form}
		return render(request,'AddMobile.html',context)
	else:
		raise Http404('you dont have permission')


def UpdateMobile(request,id):
	if request.user.is_superuser:
		try:
			mobileupdate= Mobile.objects.get(id=id)
		except Mobile.DoesNotExist:
			raise Http404

		if request.method=='POST':
			form=MobileForm(request.POST,request.FILES,instance=mobileupdate)
			if form.is_valid():
				form.save()
				return redirect('mobilestore:mobilelist')
		else:
			form=MobileForm(instance=mobileupdate)
		context={'form':form}
		return render(request,'AddMobile.html',context,)
	else:
		raise Http404('you dont have permission')

def DeleteMobile(request,id):
	try:
		mobiledelete =Mobile.objects.get(id=id)
	except Mobile.DoesNotExist:
		raise Http404
	mobiledelete.delete()
	return redirect('mobilestore:mobilelist')

MobileShop/mobilestore/templates/AddMobile.html
{% extends 'cssintro.html' %}
{% load static %}
{% load bootstrap4 %}
{% block header %}
<div class="container mt-5">
<div class="breadcrumb bg-info">

	<h4 class="text-white">New mobile</h4>
</div>
<div class="jumbotron">
  <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     {% bootstrap_form form %}
  
<button type="submit"class="btn btn-info">add mobile</button>    
 
  </form>
  
    
</div>


</div>


{% endblock %}


MobileShop/mobilestore/templates/Homepage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="{% static "e.css" %}">

    <title>Ecommerce</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark" fixed navbar>
    <img class="logo" src="{% static "logo.png" %}">
  <a class="navbar-brand" href="#">Ecommerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">store</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Cart</a>
      </li>    
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="s"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>  
</nav>

<div align="center">
<marquee 
 
     direction="right"
     loop="intro"
     scrollamount="8"
     scrolldelay="1"
     behavior="alternate";
    width="60%"
     bgcolor="#585955"
     height=50px;
     >
-----TOP DEALS-----
</marquee></div>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static "cover.jpg" %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static "cover2.jpg" %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static "cover3.jpg" %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<dir class="container" style="margin-left: 220px;">
  <dir class="row">
    <div class="col-md-3 col-sm-6">
      <div class="card text-center">
        <div class="card-block">
          <img src="{% static "m1.jpg" %}" class="img-fluid">
          <div class="card-title">
            <h3>Redmi Note6 pro</h3>
          </div>
          <div class="card-text">Say hello to Redmi Note 6 Pro - Xiaomi's first smartphone that boasts an AI-powered quad-camera. Now enjoy a smart camera experience with the AI Scene Detection feature. It helps your camera understand what it is looking at and enhances the picture automatically.Its 1.4 micrometer pixel size and wider f/1.9 apttery.</div>
          <a style="margin-top: 10px" href="#" class="btn btn-success">Read more</a>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="card text-center">
        <div class="card-block">
          <img src="{% static "oneplus.jpg" %}" class="img-fluid">
          <div class="card-title">
            <h3>One Plus 6t</h3>
          </div>
          <div class="card-text">Unlock your OnePlus 6T with the fastest in-display fingerprint sensor on any smartphone.Featuring our largest display ever and a resilient glass back, the OnePlus 6T was crafted with care and purpose. Experience a 6.41 inch Optic AMOLED display for true immersion through an 86% screen-to-body ratio, beautifully slim cut-out, and more.</div>
          <a style="margin-top: 10px" href="#" class="btn btn-success">Read more</a>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="card text-center">
        <div class="card-block">
          <img src="{% static "samg8.jpg"%}" class="img-fluid">
          <div class="card-title">
            <h3>Samsung Galaxy j8</h3>
          </div>
          <div class="card-text">Work or fun - with the Samsung J8, you can explore infinite possibilities. </div>
          <a style="margin-top: 10px" href="#" class="btn btn-success">Read more</a>
        </div>
      </div>
    </div>
  </dir>
  <br>
  <dir class="row">
    <div class="col-md-3 col-sm-6">
      <div class="card text-center">
        <div class="card-block">
          <img src= "{% static "motorolaonepower.jpg"%}" class="img-fluid">
          <div class="card-title">
            <h3>Motorola One Power</h3>
          </div>
          <div class="card-text">Indulge in a long-lasting entertainment experience with the Motorola One Power smartphone. Boasting a 15.7-cm (6.2 inch) full HD+ screen with an aspect ratio of 19:9 and a powerful 5000-mAh battery, this smartphone lets you watch your favourite video content, listen to music, or play graphic-rich video games for a long duration.</div>
          <a style="margin-top: 10px" href="#" class="btn btn-success">Read more</a>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="card text-center">
        <div class="card-block">
          <img src= "{% static "vivov11.jpg"%}" class="img-fluid">
          <div class="card-title">
            <h3>Vivo V11 </h3>
          </div>
          <div class="card-text">Click pictures like never before with the Vivo V11 Pro smartphone. </div>
          <a style="margin-top: 10px" href="#" class="btn btn-success">Read more</a>
        </div>
      </div>
    </div>
    <div class="col-md-3 col-sm-6">
      <div class="card text-center">
        <div class="card-block">
          <img src="{% static "oppor15pro.jpg"%}" class="img-fluid">
          <div class="card-title">
            <h3>Oppo R17 Pro</h3>
          </div>
          <div class="card-text">Stay connected with your loved ones, play games, keep yourself entertained for hours and do more with the OPPO R17 Pro. </div>
          <a style="margin-top: 10px" href="#" class="btn btn-success">Read more</a>
        </div>
      </div>
    </div>
  </dir>
</dir>
    <div class="footer" style="height: 5rem">
      <p class="pt-2">Copyright © 2010 by Anamika</p>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

MobileShop/mobilestore/templates/MobileDetail.html
{% extends 'cssintro.html' %}
{% load static %}

{% block header %}
<div class="container mt-5">
<div class="breadcrumb bg-info">

	<h4 class="text success">{{mobiles.Model_Name}}</h4>
</div>

<div class="jumbotron" style="background:white">
  <img class="img-fluid" src="{{ mobiles.Image.url }}" alt="Chania">
       <br>
       <br>
       <h3 class="text-info">Price:</h3>
       <h3 class= "text-dark">{{mobiles.Price}}Rs.</h3>
       <h3 class="text-info">Brand:</h3>

      <h3 class= "text-dark">{{mobiles.Brand}}</h3>
       <h3 class="text-info">features:</h3>
       <p class= "text-dark">{{mobiles.Descrption}}</p>
     {% if request.user.is_superuser %}
        <a href="{% url "mobilestore:mobileupdate" mobiles.id %}" class="btn btn-info">update</a>
        <a href="{% url "mobilestore:mobiledelete" mobiles.id %}" class="btn btn-danger">delete</a>
     {% endif %}
      </div>
  </div>
</div>


{% endblock %}


MobileShop/mobilestore/templates/MobileList.html
{% extends 'cssintro.html' %}
{% load static %}

{% block header %}
<div class="container mt-5">
<div class="breadcrumb bg-info">

	<h4 class="text success">Mobile stores</h4>
</div>
{% if mobiles %}

<div class="jumbotron" style="background:white">
    <div class="row">
    	{%for mobile in mobiles%}
      <div class="col">
       <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{{ mobile.Image.url }}"alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">{{ mobile.Model_Name }}</h5>
              <h5 class="card-title text-info ">{{ mobile.Price }} Rs</h5>
            
            <p class="card-text"></p>
            <a href="{% url 'mobilestore:MobileDetail' mobile.id %}" class="btn btn-primary">add to cart</a>

          </div>
        </div>
      </div>
  {% endfor %}
  </div>
</div>

{% else %}
<h1>there is no mobile in the store </h1>
{% endif %}
</div>
{% endblock %}


MobileShop/mobilestore/templates/cssintro.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static "e.css" %}">

    <title>Mobile Store</title>
  </head>
  <body>

<nav class="navbar navbar-expand-lg top navbar-light mb-3">
  <img src="{% static "ip.png"%}" class="image"style="height:100px; width:100px>
  <a class="navbar-brand" href="intro.css" style="color:white">Ecommerce</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto" >
      <li class="nav-item active">
        <a class="nav-link" href="{% url "mobilestore:cssintro" %}" style="color:white">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "mobilestore:mobilelist" %}" style="color:white">store</a>
      </li>
{% if request.user.is_superuser %}
 <li class="nav-item">
        <a class="nav-link" href="{% url "mobilestore:AddMobile" %}" style="color:white">addmobile</a>
      </li>
      {% endif %}
      </ul>
    <span class="navbar-text">
      <a href="" style="color:white">Login/SignUp</a>
    </span>
  </div>
</nav>
{%block header %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static "cover.jpg" %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static "cover2.jpg" %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static "cover3.jpg" %}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

<div class="container mt-3">
	<div class="jumbotron">
		ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>


  <div class="jumbotron" style="background:white">
    <div class="row">
      <div class="col">
       <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{% static "note8.jpg"%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">note series is back with another awsome design with powerful  battery </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{% static "oppor15pro.jpg"%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">presenting  you the most powerful phone designed by oppo,with most awesome and powerful cammera </p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{% static "s3.jpg"%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
      <div class="col ">
        <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{% static "p2.jpg"%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{% static "5t.jpg"%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-center mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{% static "motorolaonepower.jpg"%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
   
    </div>
  </div>

</div>

<marquee 
 
     direction="right"
     loop="intro"
     scrollamount="8"
     scrolldelay="1"
     behavior="alternate";
    width="100%"
     bgcolor="#2980b9"
     height=200px;
    >
<img  src="{% static "cover4.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover4.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover4.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover5.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover5.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover4.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover4.jpg"%}" width="120" height="80" alt="Card image cap">
<img  src="{% static "cover5.jpg"%}" width="120" height="80" alt="Card image cap">

</marquee>

{% endblock %}

{% block footer %}
<footer class="footer text-center bg-dark" style="height:4rem">
    <h5 class="text-white pt-4">Ecomerce</h5>
</footer>
{% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>